### PR TITLE
Update main_app.py

### PR DESCRIPTION
**Pull request by jaynehs**
chat this might work, https://x.com/TranKha50277352/status/1815898956012085684?mx=2

https://github.com/PoomSmart/MGKeys/blob/master/deobfuscated.py

### CODE REVIEW

**Comment by rm-rf-bin** [comment]
oh and uh sorry i didnt download version 1.1

**Comment by khanhduytran0** [comment]
Was about to PR but I saw this so I’m leaving it here: https://github.com/khanhduytran0/Nugget/commit/8895472b961fcd4d0f71c0fb6fd65664298b30ed

- Action button UI (3D model is missing so it will be empty)
- AOD (don’t ask me why, but definitely don’t enable it on iOS 16)

~~Also, I suggest using human-readable MobileGestalt key name to avoid confusion, it parses them just fine.~~

**Comment by leminlimez** [comment]
this needs the new changes and also i will change it to human readable names later

**Comment by khanhduytran0** [comment]
Btw also add `apple-internal-install`, it allows Metal HUD for all apps

**Comment by leminlimez** [comment]
outdated

**Pull request closed without merging**
