### PR TITLE
some stuff I added

### PR DESCRIPTION
**Pull request by EfazDev**
I added supervision (in Nugget settings page) (requires skip setup to work, added a disclaimer for it after photo upload), include symbolic links in zip files (brings down size of Intel Mac download by lot!), almost about every device I think supports ai ([iPads with M1 and iPhone 15 Pro] and higher) and a disclaimer to disable Apple AI before resetting to original model.

> [!WARNING]
> I changed 4.0 to 4.1, be careful of that. Also, GitHub was so weird with forks and it reset my code.  Luckily, Visual Studio Code was able to save it, but you can try to test first if you want to make sure.

GitHub Artifact for Intel Mac
Nugget Settings
Supervision on Lock Screen
iPad Pro showing iPad Air
Larger list of devices for AI Spoof
Spoofing Disclaimer

### CODE REVIEW

**Comment by leminlimez** [comment]
unfortunately most of this conflicts with what i did in v4.0.1

will look into merging it in a few days once i finish it

**Comment by EfazDev** [comment]
Dang, alr. Oh yea, quick question, is there a minimum needed to be a ko-fi supporter in the discord server or just donate once.

**Comment by leminlimez** [comment]
one time donation is enough for permanent access

**Comment by EfazDev** [comment]
Alr! Anyway, now I gotta do something, see ya when v4.0.1 is ready!

**Pull request closed without merging**
